[workspace]
resolver = "2"
members = ["./apps/api", "./apps/desktop/src-tauri"]

[workspace.dependencies]
# 序列化/反序列化
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

# 错误处理
anyhow = "1.0.97"
thiserror = "2.0.12"

# 日志
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = [
    "env-filter",
    "local-time",
] }
