version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    volumes:
      - ../apps/web:/app/apps/web
      - ../packages:/app/packages
      - web_node_modules:/app/apps/web/node_modules
      - packages_node_modules:/app/packages/node_modules

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/doc_editor
      - JWT_SECRET=your_jwt_secret_here
      - RUST_LOG=info
    volumes:
      - ../apps/api:/app/apps/api

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=doc_editor
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  web_node_modules:
  packages_node_modules:
