
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    ports:
      - "3000:80"
    # TODO: Uncomment this when the api is ready
    # depends_on:
    #   - api
    environment:
      - API_URL=http://api:8000

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/doc_editor
      - JWT_SECRET=your_jwt_secret_here
      - RUST_LOG=info
    volumes:
      - ../apps/api:/app/apps/api

  postgres:
    image: bitnami/postgresql:latest
    container_name: doc_editor_backend
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: doc_editor
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
